/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trollingcont.servicebuilder.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeRight service. Represents a row in the &quot;LS_EmployeeRight&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.trollingcont.servicebuilder.model.impl.EmployeeRightModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.trollingcont.servicebuilder.model.impl.EmployeeRightImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeRight
 * @generated
 */
@ProviderType
public interface EmployeeRightModel extends BaseModel<EmployeeRight> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee right model instance should use the {@link EmployeeRight} interface instead.
	 */

	/**
	 * Returns the primary key of this employee right.
	 *
	 * @return the primary key of this employee right
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee right.
	 *
	 * @param primaryKey the primary key of this employee right
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the right ID of this employee right.
	 *
	 * @return the right ID of this employee right
	 */
	public long getRightId();

	/**
	 * Sets the right ID of this employee right.
	 *
	 * @param rightId the right ID of this employee right
	 */
	public void setRightId(long rightId);

	/**
	 * Returns the employee ID of this employee right.
	 *
	 * @return the employee ID of this employee right
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee right.
	 *
	 * @param employeeId the employee ID of this employee right
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the product type ID of this employee right.
	 *
	 * @return the product type ID of this employee right
	 */
	public long getProductTypeId();

	/**
	 * Sets the product type ID of this employee right.
	 *
	 * @param productTypeId the product type ID of this employee right
	 */
	public void setProductTypeId(long productTypeId);

}