/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trollingcont.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductType service. Represents a row in the &quot;LS_ProductType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.trollingcont.servicebuilder.model.impl.ProductTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.trollingcont.servicebuilder.model.impl.ProductTypeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductType
 * @generated
 */
@ProviderType
public interface ProductTypeModel extends BaseModel<ProductType> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product type model instance should use the {@link ProductType} interface instead.
	 */

	/**
	 * Returns the primary key of this product type.
	 *
	 * @return the primary key of this product type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product type.
	 *
	 * @param primaryKey the primary key of this product type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this product type.
	 *
	 * @return the uuid of this product type
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this product type.
	 *
	 * @param uuid the uuid of this product type
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the product type ID of this product type.
	 *
	 * @return the product type ID of this product type
	 */
	public long getProductTypeId();

	/**
	 * Sets the product type ID of this product type.
	 *
	 * @param productTypeId the product type ID of this product type
	 */
	public void setProductTypeId(long productTypeId);

	/**
	 * Returns the name of this product type.
	 *
	 * @return the name of this product type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this product type.
	 *
	 * @param name the name of this product type
	 */
	public void setName(String name);

}