/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trollingcont.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Post service. Represents a row in the &quot;LS_Post&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.trollingcont.servicebuilder.model.impl.PostModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.trollingcont.servicebuilder.model.impl.PostImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Post
 * @generated
 */
@ProviderType
public interface PostModel extends BaseModel<Post> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a post model instance should use the {@link Post} interface instead.
	 */

	/**
	 * Returns the primary key of this post.
	 *
	 * @return the primary key of this post
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this post.
	 *
	 * @param primaryKey the primary key of this post
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this post.
	 *
	 * @return the uuid of this post
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this post.
	 *
	 * @param uuid the uuid of this post
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the post ID of this post.
	 *
	 * @return the post ID of this post
	 */
	public long getPostId();

	/**
	 * Sets the post ID of this post.
	 *
	 * @param postId the post ID of this post
	 */
	public void setPostId(long postId);

	/**
	 * Returns the name of this post.
	 *
	 * @return the name of this post
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this post.
	 *
	 * @param name the name of this post
	 */
	public void setName(String name);

}