/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trollingcont.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Purchase service. Represents a row in the &quot;LS_Purchase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.trollingcont.servicebuilder.model.impl.PurchaseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.trollingcont.servicebuilder.model.impl.PurchaseImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Purchase
 * @generated
 */
@ProviderType
public interface PurchaseModel extends BaseModel<Purchase> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a purchase model instance should use the {@link Purchase} interface instead.
	 */

	/**
	 * Returns the primary key of this purchase.
	 *
	 * @return the primary key of this purchase
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this purchase.
	 *
	 * @param primaryKey the primary key of this purchase
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this purchase.
	 *
	 * @return the uuid of this purchase
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this purchase.
	 *
	 * @param uuid the uuid of this purchase
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the purchase ID of this purchase.
	 *
	 * @return the purchase ID of this purchase
	 */
	public long getPurchaseId();

	/**
	 * Sets the purchase ID of this purchase.
	 *
	 * @param purchaseId the purchase ID of this purchase
	 */
	public void setPurchaseId(long purchaseId);

	/**
	 * Returns the product ID of this purchase.
	 *
	 * @return the product ID of this purchase
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this purchase.
	 *
	 * @param productId the product ID of this purchase
	 */
	public void setProductId(long productId);

	/**
	 * Returns the employee ID of this purchase.
	 *
	 * @return the employee ID of this purchase
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this purchase.
	 *
	 * @param employeeId the employee ID of this purchase
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the date purchased of this purchase.
	 *
	 * @return the date purchased of this purchase
	 */
	public Date getDatePurchased();

	/**
	 * Sets the date purchased of this purchase.
	 *
	 * @param datePurchased the date purchased of this purchase
	 */
	public void setDatePurchased(Date datePurchased);

	/**
	 * Returns the purchase type of this purchase.
	 *
	 * @return the purchase type of this purchase
	 */
	public long getPurchaseType();

	/**
	 * Sets the purchase type of this purchase.
	 *
	 * @param purchaseType the purchase type of this purchase
	 */
	public void setPurchaseType(long purchaseType);

}